### ISSUE TITLE
استفاده از منبع Chocolate4U

### ISSUE THREAD

**Issue by M-Sadegh-M** [mer30hamid/v2rayN-Routing-Rules-Generator#2]
سلام وقت بخیر
میخواستم پیشنهاد کنم اگه امکانش هست از منبع زیر استفاده کنید
کامل تر و جامع تر هست، تبلیغات را بهتر پوشش میده همچنین سایت های مخرب
کل منبع فعلی شما را هم داخلش داره + سایر ایپی ها و دامنه های دیگه

[Chocolate4U](https://github.com/Chocolate4U)

**Comment by mer30hamid** [comment]
سلام،
منم این پروژه رو دیده بودم، ممنون، در مورد سایت های ایرانی باید بگم که عینا از منبعی استفاده می کنه که من استفاده کردم، متن این اسکریپت رو ببینید:
```
https://github.com/Chocolate4U/Iran-v2ray-rules/blob/main/scripts/generate-ir-domains.sh
```
هدف اسکریپت من، تولید رول‌ها برای حل مشکل سایت های ایرانی هست، اینکه وقتی وارد سایتی می‌شیم، بهمون ایراد نگیره که داری از وی پی ان استفاده می کنی و ...
اگر غلظت لیست ادبلاکر و ... رو زیاد کنم، دو تا مشکل پیش میاد:
1. زیاد شدن مصرف منابع (پهنای باند برای دانلود رول ها و رم برای کلاینت)
2. بیشتر شدن احتمال اینکه خیلی از سایت ها شروع کنن به اذیت کردن که چرا ادبلاکر داری و ... که در واقع مجبورت می کنن که بری وی پی ان رو خاموش کنی (تناقض با هدف این اسکریپت!)
